# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# owned by spite897

[mgr]

keymap = [
	{ on = "<Esc>", run = "escape",             desc = "Exit visual mode, clear selection, or cancel search" },
	{ on = "<C-[>", run = "escape",             desc = "Exit visual mode, clear selection, or cancel search" },

	{ on = "q",     run = "close",               desc = "Quit the process" },
	{ on = "Q",     run = "quit --no-cwd-file", desc = "Quit without outputting cwd-file" },

	{ on = "<C-c>", run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "<C-z>", run = "suspend",            desc = "Suspend the process" },

	# Hopping
	{ on = "e", run = "arrow prev", desc = "Previous file" },
	{ on = "n", run = "arrow next", desc = "Next file" },

	{ on = [ "g", "g" ], run = "arrow top", desc = "Go to top" },
	{ on = "G",          run = "arrow bot", desc = "Go to bottom" },

	# Navigation
	{ on = "h", run = "leave", desc = "Back to the parent directory" },
	{ on = "i", run = "plugin smart-enter", desc = "Enter the child directory" },

	{ on = [ "`", "`" ], run = "back",    desc = "Back to previous directory" },
	{ on = [ "`", "~" ], run = "forward", desc = "Forward to next directory" },

	# Toggle
	{ on = "<Space>", run = [ "toggle", "arrow next" ], desc = "Toggle the current selection state" },
	{ on = "<C-a>",   run = "toggle_all --state=on",    desc = "Select all files" },
	{ on = "<C-r>",   run = "toggle_all",               desc = "Invert selection of all files" },

	# Visual mode
	{ on = "v", run = "visual_mode",         desc = "Enter visual mode (selection mode)" },
	{ on = "V", run = "visual_mode --unset", desc = "Enter visual mode (unset mode)" },

	# Seeking
	{ on = "E", run = "seek -3", desc = "Seek up 3 units in the preview" },
	{ on = "N", run = "seek 3",  desc = "Seek down 3 units in the preview" },

	# Spotting
	{ on = "<Tab>", run = "spot", desc = "Spot hovered file" },

	# Operation
	{ on = "o",         run = "open --interactive",          desc = "Open selected files" },
	{ on = "O",         run = "open --interactive",          desc = "Open selected files interactively" },
	{ on = "y",         run = "yank",                        desc = "Yank selected files (copy)" },
	{ on = "x",         run = "yank --cut",                  desc = "Yank selected files (cut)" },
	{ on = [ "d", "d" ],run = "remove --force --permently",                      desc = "Trash selected files" },
	{ on = "a",         run = "create",                      desc = "Create a file (ends with / for directories)" },
	{ on = "r",         run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" },
	{ on = "R",         run = "rename --empty=stem --cursor=start",  desc = "Rename selected file(s)" },
	{ on = ";",         run = "shell --interactive",         desc = "Run a shell command" },
	{ on = ":",         run = "shell --block --interactive", desc = "Run a shell command (block until finishes)" },
    #{ on = "D",         run  = "plugin diff",                desc = "Diff the selected with the hovered file"},
    { on   = "f",      run  = "plugin jump-to-char",         desc = "Jump to char"},


	{ on =  "p",          run = ["paste", "unyank"],                desc = "Paste yanked files" },
	{ on =  [ "P", "p" ], run = "paste --force --follow",           desc = "Paste yanked files (overwrite if the destination exists)" },
	{ on =  [ "P", "c" ], run = "unyank",                           desc = "Cancel the yank status" },
	{ on =  [ "P", "l", "a" ], run = "link",                        desc = "Symlink the absolute path of yanked files" },
	{ on =  [ "P", "l", "r" ], run = "link --relative",             desc = "Symlink the relative path of yanked files" },
	{ on =  [ "P", "l", "h" ], run = "hardlink",                    desc = "Hardlink yanked files" },

	# Linemode
	{ on = [ "M", "s", "s" ], run = "linemode size",        desc = "Linemode: size" },
	{ on = [ "M", "s", "p" ], run = "linemode permissions", desc = "Linemode: permissions" },
	{ on = [ "M", "s", "b" ], run = "linemode btime",       desc = "Linemode: btime" },
	{ on = [ "M", "s", "m" ], run = "linemode mtime",       desc = "Linemode: mtime" },
	{ on = [ "M", "s", "o" ], run = "linemode owner",       desc = "Linemode: owner" },
	{ on = [ "M", "s", "n" ], run = "linemode none",        desc = "Linemode: none" },
	{ on = [ "M", "s", "h" ], run = "hidden toggle",        desc = "Toggle the visibility of hidden files" },

	{ on = [ "M", "F" ], run = "search_do --via=fd", desc = "Flat view" },
	#{ on = [ "M", "f", "f" ], run = "filter --smart", desc = "Filter files" },
	{ on = [ "M", "f", "f"],         run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = [ "M", "f", "c"],         run = "search --via=rg",             desc = "Search files by content via ripgrep" },

	{ on = [ "M", "o", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime" ], desc = "Sort by modified time" },
	{ on = [ "M", "o", "M" ], run = [ "sort mtime --reverse", "linemode mtime" ],    desc = "Sort by modified time (reverse)" },
	{ on = [ "M", "o", "b" ], run = [ "sort btime --reverse=no", "linemode btime" ], desc = "Sort by birth time" },
	{ on = [ "M", "o", "B" ], run = [ "sort btime --reverse", "linemode btime" ],    desc = "Sort by birth time (reverse)" },
	{ on = [ "M", "o", "e" ], run = "sort extension --reverse=no",                   desc = "Sort by extension" },
	{ on = [ "M", "o", "E" ], run = "sort extension --reverse",                      desc = "Sort by extension (reverse)" },
	{ on = [ "M", "o", "a" ], run = "sort alphabetical --reverse=no",                desc = "Sort alphabetically" },
	{ on = [ "M", "o", "A" ], run = "sort alphabetical --reverse",                   desc = "Sort alphabetically (reverse)" },
	{ on = [ "M", "o", "n" ], run = "sort natural --reverse=no",                     desc = "Sort naturally" },
	{ on = [ "M", "o", "N" ], run = "sort natural --reverse",                        desc = "Sort naturally (reverse)" },
	{ on = [ "M", "o", "s" ], run = [ "sort size --reverse=no", "linemode size" ],   desc = "Sort by size" },
	{ on = [ "M", "o", "S" ], run = [ "sort size --reverse", "linemode size" ],      desc = "Sort by size (reverse)" },
	{ on = [ "M", "o", "r" ], run = "sort random --reverse=no",                      desc = "Sort randomly" },

    { on = [ "P", "t" ], run = "plugin eza-preview",  desc = "Toggle tree/list dir preview" },
    { on = [ "P", "=" ], run = "plugin eza-preview inc-level", desc = "Increment tree level" },
    { on = [ "P", "-" ], run = "plugin eza-preview dec-level", desc = "Decrement tree level" },
    { on = [ "P", "$" ], run = "plugin eza-preview toggle-follow-symlinks", desc = "Toggle tree follow symlinks" },
    { on = [ "P", "h" ], run = "plugin eza-preview toggle-hidden", desc = "Toggle hidden files" },
    { on = [ "P", "g", "i" ], run = "plugin eza-preview toggle-git-ignore", desc = "Toggle .gitignore files" },
    { on = [ "P", "g", "s" ], run = "plugin eza-preview toggle-git-status", desc = "Toggle showing git status" },

	# Copy
	{ on = [ "Y", "c" ], run = "copy path",             desc = "Copy the file path" },
	{ on = [ "Y", "d" ], run = "copy dirname",          desc = "Copy the directory path" },
	{ on = [ "Y", "f" ], run = "copy filename",         desc = "Copy the filename" },
	{ on = [ "Y", "n" ], run = "copy name_without_ext", desc = "Copy the filename without extension" },

	# Find
	{ on = "/", run = "find --smart",            desc = "Find next file" },
	{ on = "?", run = "find --previous --smart", desc = "Find previous file" },
	{ on = "k", run = "find_arrow",              desc = "Next found" },
	{ on = "K", run = "find_arrow --previous",   desc = "Previous found" },

	# Goto
	{ on = [ "g", "h" ],       run = "cd ~",             desc = "Go home" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",     desc = "Go ~/.config" },
	{ on = [ "g", "d" ],       run = "cd ~/Downloads",   desc = "Go ~/Downloads" },
	{ on = [ "g", "<Space>" ], run = "cd --interactive", desc = "Jump interactively" },
	{ on = [ "g", "f" ],       run = "follow",           desc = "Follow hovered symlink" },
	{ on = [ "g", "w" ],       run = "cd ~/Documents",   desc = "Go ~/Documents" },
	{ on = [ "g", "z" ],       run = "plugin fzf",       desc = "Jump to a file/directory via fzf" },
	{ on = [ "g", "Z" ],       run = "plugin zoxide",    desc = "Jump to a directory via zoxide" },

	# Tabs
	{ on = [ "t", "t" ],  run = "tab_create --current", desc = "Create a new tab with CWD" },

	{ on = [ "t", "1" ], run = "tab_switch 0", desc = "Switch to first tab" },
	{ on = [ "t", "2" ], run = "tab_switch 1", desc = "Switch to second tab" },
	{ on = [ "t", "3" ], run = "tab_switch 2", desc = "Switch to third tab" },
	{ on = [ "t", "4" ], run = "tab_switch 3", desc = "Switch to fourth tab" },
	{ on = [ "t", "5" ], run = "tab_switch 4", desc = "Switch to fifth tab" },
	{ on = [ "t", "6" ], run = "tab_switch 5", desc = "Switch to sixth tab" },
	{ on = [ "t", "7" ], run = "tab_switch 6", desc = "Switch to seventh tab" },
	{ on = [ "t", "8" ], run = "tab_switch 7", desc = "Switch to eighth tab" },
	{ on = [ "t", "9" ], run = "tab_switch 8", desc = "Switch to ninth tab" },

	{ on = [ "t", "h" ], run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
	{ on = [ "t", "i" ], run = "tab_switch 1 --relative",  desc = "Switch to next tab" },

	{ on = [ "t", "H" ], run = "tab_swap -1", desc = "Swap current tab with previous tab" },
	{ on = [ "t", "I" ], run = "tab_swap 1",  desc = "Swap current tab with next tab" },

	# Tasks
	{ on = "w", run = "tasks:show", desc = "Show task manager" },

	# Help
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[tasks]

keymap = [
	{ on = "<Esc>", run = "close", desc = "Close task manager" },
	{ on = "<C-[>", run = "close", desc = "Close task manager" },
	{ on = "w",     run = "close", desc = "Close task manager" },

	{ on = "e", run = "arrow prev", desc = "Previous task" },
	{ on = "n", run = "arrow next", desc = "Next task" },

	{ on = "o",       run = "inspect", desc = "Inspect the task" },
	{ on = "d",       run = "cancel",  desc = "Cancel the task" },

	# Help
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[spot]

keymap = [
	{ on = "<Esc>", run = "close", desc = "Close the spot" },
	{ on = "<C-[>", run = "close", desc = "Close the spot" },
	{ on = "<Tab>", run = "close", desc = "Close the spot" },

	{ on = "e", run = "arrow prev", desc = "Previous line" },
	{ on = "n", run = "arrow next", desc = "Next line" },
	{ on = "h", run = "swipe prev", desc = "Swipe to previous file" },
	{ on = "i", run = "swipe next", desc = "Swipe to next file" },

	# Copy
	{ on = "y", run = "copy cell", desc = "Copy selected cell" },

	# Help
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[pick]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "Cancel pick" },
	{ on = "<C-[>",   run = "close",          desc = "Cancel pick" },
	{ on = "o",       run = "close --submit", desc = "Submit the pick" },
	{ on = "<Enter>", run = "close --submit", desc = "Submit the pick" },

	{ on = "e", run = "arrow prev", desc = "Previous option" },
	{ on = "n", run = "arrow next", desc = "Next option" },

	# Help
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[input]

keymap = [
	{ on = "<Enter>", run = "close --submit", desc = "Submit input" },
	{ on = "<S-Enter>", run = "close",        desc = "Close input" },
	{ on = "<Esc>",   run = "escape",         desc = "Back to normal mode, or cancel input" },
	{ on = "<C-[>",   run = "escape",         desc = "Back to normal mode, or cancel input" },

	# Mode
	{ on = "l", run = "insert",                          desc = "Enter insert mode" },
	{ on = "L", run = [ "move first-char", "insert" ],   desc = "Move to the BOL, and enter insert mode" },
	{ on = "a", run = "insert --append",                 desc = "Enter append mode" },
	{ on = "A", run = [ "move eol", "insert --append" ], desc = "Move to the EOL, and enter append mode" },
	{ on = "v", run = "visual",                          desc = "Enter visual mode" },
	{ on = "r", run = "replace",                         desc = "Replace a single character" },

	# Selection
	{ on = "V",     run = [ "move bol", "visual", "move eol" ], desc = "Select from BOL to EOL" },

	# Character-wise movement
	{ on = "h",       run = "move -1", desc = "Move back a character" },
	{ on = "i",       run = "move 1",  desc = "Move forward a character" },

	# Word-wise movement
	{ on = "b",     run = "backward",                    desc = "Move back to the start of the current or previous word" },
	{ on = "B",     run = "backward --far",              desc = "Move back to the start of the current or previous WORD" },
	{ on = "w",     run = "forward",                     desc = "Move forward to the start of the next word" },
	{ on = "W",     run = "forward --far",               desc = "Move forward to the start of the next WORD" },
	{ on = "e",     run = "forward --end-of-word",       desc = "Move forward to the end of the current or next word" },
	{ on = "E",     run = "forward --far --end-of-word", desc = "Move forward to the end of the current or next WORD" },

	# Line-wise movement
	{ on = "0",      run = "move bol",        desc = "Move to the BOL" },
	{ on = "$",      run = "move eol",        desc = "Move to the EOL" },

	# Delete
	{ on = "<Backspace>", run = "backspace",         desc = "Delete the character before the cursor" },
	{ on = "<Delete>",    run = "backspace --under", desc = "Delete the character under the cursor" },

	# Kill
	{ on = "<C-u>", run = "kill bol",      desc = "Kill backwards to the BOL" },
	{ on = "<C-k>", run = "kill eol",      desc = "Kill forwards to the EOL" },
	{ on = "<C-w>", run = "kill backward", desc = "Kill backwards to the start of the current word" },
	{ on = "<A-d>", run = "kill forward",  desc = "Kill forwards to the end of the current word" },

	# Cut/Yank/Paste
	{ on = "d", run = "delete --cut",                                      desc = "Cut selected characters" },
	{ on = "D", run = [ "delete --cut", "move eol" ],                      desc = "Cut until EOL" },
	{ on = "c", run = "delete --cut --insert",                             desc = "Cut selected characters, and enter insert mode" },
	{ on = "C", run = [ "delete --cut --insert", "move eol" ],             desc = "Cut until EOL, and enter insert mode" },
	{ on = "s", run = [ "delete --cut --insert", "move 1" ],               desc = "Cut current character, and enter insert mode" },
	{ on = "S", run = [ "move bol", "delete --cut --insert", "move eol" ], desc = "Cut from BOL until EOL, and enter insert mode" },
	{ on = "x", run = [ "delete --cut", "move 1 --in-operating" ],         desc = "Cut current character" },
	{ on = "y", run = "yank",                                              desc = "Copy selected characters" },
	{ on = "p", run = "paste",                                             desc = "Paste copied characters after the cursor" },
	{ on = "P", run = "paste --before",                                    desc = "Paste copied characters before the cursor" },

	# Undo/Redo
	{ on = "u",     run = "undo", desc = "Undo the last operation" },
	{ on = "<C-r>", run = "redo", desc = "Redo the last operation" },

	# Help
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[confirm]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "Cancel the confirm" },
	{ on = "<C-[>",   run = "close",          desc = "Cancel the confirm" },
	{ on = "<Enter>", run = "close --submit", desc = "Submit the confirm" },

	{ on = "n", run = "close",          desc = "Cancel the confirm" },
	{ on = "y", run = "close --submit", desc = "Submit the confirm" },

	{ on = "h", run = "arrow prev", desc = "Previous line" },
	{ on = "i", run = "arrow next", desc = "Next line" },

	# Help
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[cmp]

keymap = [
	{ on = "<Tab>",   run = "close --submit",                             desc = "Submit the completion" },
	{ on = "<Enter>", run = [ "close --submit", "input:close --submit" ], desc = "Complete and submit the input" },

	{ on = "<C-e>", run = "arrow prev", desc = "Previous item" },
	{ on = "<C-n>", run = "arrow next", desc = "Next item" },

	# Help
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[help]

keymap = [
	{ on = "<Esc>", run = "escape", desc = "Clear the filter, or hide the help" },
	{ on = "<C-[>", run = "escape", desc = "Clear the filter, or hide the help" },
	{ on = "q",     run = "escape", desc = "Clear the filter, or hide the help" },

	# Navigation
	{ on = "e", run = "arrow prev", desc = "Previous line" },
	{ on = "n", run = "arrow next", desc = "Next line" },
    { on = [ "g", "g" ],    run = "arrow top", desc = "" },
    { on = "G" ,            run = "arrow bot", desc="" },

	# Filtering
	{ on = "f", run = "filter", desc = "Filter help items" },
]
